// Resource library: user avatar images.
//
// Avatars are generated by DiceBear (https://dicebear.com) from a stable seed —
// the user's display name — so every user gets a unique, deterministic image
// with no storage and no API key. The provider config lives in ./avatars.json
// so the seed scripts (plain .mjs) can build the exact same URLs from one
// source of truth. Real users who upload their own picture keep it; this
// library is the avatar source for bot-generated players.
import config from "@/lib/avatars.json";

export const AVATAR_BASE_URL = config.baseUrl;

// Deterministic avatar URL for a seed (same seed → same image).
export function avatarUrl(seed: string): string {
  return `${AVATAR_BASE_URL}?seed=${encodeURIComponent(seed || "anon")}`;
}
